import type { Metadata } from "next";
import { lato } from "@/app/ui/fonts";
import ClientRootLayout from "@/app/client-root-layout";

export const metadata: Metadata = {
  title: "TicketFlicks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${lato.className} scroll-smooth scroll-pt-[20%]`}
      style={lato.style}
    >
      <body className="desktop:pt-[196px] laptop:pt-[140px] tablet:pt-[150px] phone:pt-[97px] overflow-x-hidden h-full">
        <ClientRootLayout>{children}</ClientRootLayout>
      </body>
    </html>
  );
}

