import type { Metadata } from "next";
import "@/app/styles/index.css";
import { inter } from "@/app/ui/fonts"
import Navbar from "@/app/components/Navbar";

export const metadata: Metadata = {
  title: "TicketFlicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className}`} style={inter.style}>
      <body className="bg-gradient-to-b from-black text-white from-15% via-primary via-85% to-black h-screen desktop:pt-[196px]">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
